import Head from 'next/head'
import { useState } from 'react'
import Header from '../components/Header'
import Gallery from '../components/Gallery'
import Login from '../components/Login'
import Register from '../components/Register'
import Cart from '@/components/Cart'
import Orders from '@/components/Orders'




export default function Home() {
 
  const products = [
    {
      id: 1,
      name: "Name",
      image:"/next.svg",
      description: "Esto es una hermosa descripcion de este producto que es muy caro",
      price: "100"
    },
    {
      id: 2,
      name: "Name2",
      image:"/next.svg",
      description: "Esto es una hermosa descripcion de un producto que es incluso mas caro que el anterior",
      price: "2000"
    },
    {
      id: 1,
      name: "Name",
      image:"/next.svg",
      description: "Esto es una hermosa descripcion de este producto que es muy caro",
      price: "100"
    },
    {
      id: 2,
      name: "Name2",
      image:"/next.svg",
      description: "Esto es una hermosa descripcion de un producto que es incluso mas caro que el anterior",
      price: "2000"
    },
    {
      id: 1,
      name: "Name",
      image:"/next.svg",
      description: "Esto es una hermosa descripcion de este producto que es muy caro",
      price: "100"
    },
    {
      id: 2,
      name: "Name2",
      image:"/next.svg",
      description: "Esto es una hermosa descripcion de un producto que es incluso mas caro que el anterior",
      price: "2000"
    },
    {
      id: 1,
      name: "Name",
      image:"/next.svg",
      description: "Esto es una hermosa descripcion de este producto que es muy caro",
      price: "100"
    },
    {
      id: 2,
      name: "Name2",
      image:"/next.svg",
      description: "Esto es una hermosa descripcion de un producto que es incluso mas caro que el anterior",
      price: "2000"
    }
  ]
  const[route, setRoute] = useState("/");
  const [cartProducts, setCart] = useState([]);
  const orders =[ 
    {
      id: 1,
      products: [
          "casa",
          "otro",
          "y otro"
      ],
      prices: [
          "5",
          "1.5",
          "2.0"
      ],
      total: 500
    },
    {
      id: 1,
      products: [
          "casa",
          "otro",
          "y otro"
      ],
      prices: [
          "5",
          "1.5",
          "2.0"
      ],
      total: 500
    }
  ]
  return (
    <>

      <Head>
        <title>modo cubano</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header setRoute={setRoute} route={route}/>
      <main >
        {route==="/" && <Gallery products={products} setCart={setCart}/>}
        {route==="Login" && <Login setRoute={setRoute}/>}
        {route==="Register" && <Register setRoute={setRoute}/>}
        {route==="Cart" && <Cart products={cartProducts}/>}
        {route==="Orders" && <Orders orders={orders}/>}


      </main>

    </>
  )
}
