import Head from 'next/head'
import { useState } from 'react'
import Header from '../components/Header'
import Gallery from '../components/Gallery'
import Login from '../components/Login'
import Register from '../components/Register'
import Cart from '@/components/Cart'
import Orders from '@/components/Orders'
import { CartProductsProvider } from '@/context/CartProductsContext'


export default function Home() {
  
  const[route, setRoute] = useState("/");

  const orders = [ 
    {
      id: 1,
      products: [
          "casa",
          "otro",
          "y otro"
      ],
      prices: [
          "5",
          "1.5",
          "2.0"
      ],
      total: 500
    },
    {
      id: 1,
      products: [
          "casa",
          "otro",
          "y otro"
      ],
      prices: [
          "5",
          "1.5",
          "2.0"
      ],
      total: 500
    }
  ]

  return (
    <>

      <Head>
        <title>modo cubano</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CartProductsProvider>
        <Header setRoute={setRoute} route={route}/>
        <main >
          {route==="/" && <Gallery />}
          {route==="Login" && <Login setRoute={setRoute}/>}
          {route==="Register" && <Register setRoute={setRoute}/>}
          {route==="Cart" && <Cart />}
          {route==="Orders" && <Orders orders={orders}/>}
        </main>
      </CartProductsProvider>

    </>
  )
}
